// Generated by CoffeeScript 2.0.0-beta2
'use strict';
var Generator, chalk, yosay;

Generator = require('yeoman-generator');

chalk = require('chalk');

yosay = require('yosay');

module.exports = class extends Generator {
  prompting() {
    var propmpts;
    this.log(yosay(`Welcome to the doozie ${chalk.red('generator-puelkin')} generator!`));
    propmpts = [
      {
        type: 'confirm',
        name: 'someAnswer',
        message: 'Would you like to enable this option?',
        default: true
      }
    ];
    return this.prompt(propmts).then((props) => {
      return this.props = props;
    });
  }

  writing() {
    return this.fs.copy(this.templatePath('dummyfile.txt'), this.destinationPath('dummyfile.txt'));
  }

  install() {
    return this.installDependencies();
  }

};
